{{- if and .Values.ports (gt (len .Values.ports) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    app: {{ .Values.appName }}
  ports:
    {{- range $port := .Values.ports }}
    - port: {{ $port.containerPort }}
      name: {{ $port.name | default "port" }}
      targetPort: {{ $port.containerPort }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      protocol: {{ $port.protocol | default "TCP" }}
    {{- end}}
{{- end}}